/**
 * Built-in AI Trading Team templates (spec §18).
 * Admin templates live in RTDB (`aiTradingTeamTemplates/admin`) and are merged
 * over these by the API. Templates are editable by the user after instantiation.
 */

import { TeamTemplate } from "./types";

export const BUILTIN_TEAM_TEMPLATES: TeamTemplate[] = [
    {
        id: "tpl-xauusd-scalping",
        name: "XAUUSD Scalping Team",
        description:
            "Fast gold scalping desk: M5 entries, M15 confirmation, H1 context with smart-money, liquidity and hard risk validation.",
        scope: "builtin",
        config: {
            market: "XAUUSD",
            style: "scalping",
            entryTimeframe: "M5",
            confirmationTimeframe: "M15",
            contextTimeframe: "H1",
            riskProfile: "balanced",
            behavior: "risk-first",
            intents: ["scalping", "smart-money", "setup-validation", "risk"],
            behaviorRules: { requireRiskValidation: true },
        },
        agentIds: [
            "market-regime",
            "smart-money",
            "price-action",
            "liquidity",
            "risk-manager",
            "contrarian",
            "chief-analyst",
        ],
        tags: ["gold", "scalping", "popular"],
    },
    {
        id: "tpl-forex-intraday",
        name: "Forex Intraday Team",
        description: "Intraday FX desk with technical + regime focus and macro event awareness.",
        scope: "builtin",
        config: {
            market: "EURUSD",
            style: "intraday",
            entryTimeframe: "M15",
            confirmationTimeframe: "H1",
            contextTimeframe: "H4",
            riskProfile: "balanced",
            behavior: "evidence-weighted",
            intents: ["technical", "macro", "regime", "setup-validation"],
        },
        agentIds: [
            "market-regime",
            "technical-analyst",
            "price-action",
            "macro-news",
            "risk-manager",
            "setup-validator",
            "chief-analyst",
        ],
        tags: ["forex", "intraday"],
    },
    {
        id: "tpl-crypto-momentum",
        name: "Crypto Momentum Team",
        description: "24/7 crypto momentum desk: regime, quant and liquidity emphasis with research-grade validation.",
        scope: "builtin",
        config: {
            market: "BTCUSD",
            style: "intraday",
            entryTimeframe: "M30",
            confirmationTimeframe: "H1",
            contextTimeframe: "H4",
            riskProfile: "aggressive",
            behavior: "evidence-weighted",
            intents: ["quant", "regime", "liquidity", "technical"],
        },
        agentIds: [
            "market-regime",
            "quant-research",
            "technical-analyst",
            "liquidity",
            "smart-money",
            "risk-manager",
            "chief-analyst",
        ],
        tags: ["crypto", "momentum"],
    },
    {
        id: "tpl-smart-money-research",
        name: "Smart Money Research Team",
        description: "Institutional-footprint research desk: structure, liquidity, sweeps and contrarian review.",
        scope: "builtin",
        config: {
            market: "XAUUSD",
            style: "swing",
            entryTimeframe: "M15",
            confirmationTimeframe: "H1",
            contextTimeframe: "H4",
            riskProfile: "balanced",
            behavior: "consensus",
            intents: ["smart-money", "liquidity", "structure", "research"],
        },
        agentIds: [
            "smart-money",
            "liquidity",
            "price-action",
            "contrarian",
            "strategy-research",
            "risk-manager",
            "chief-analyst",
        ],
        tags: ["smart-money", "research"],
    },
    {
        id: "tpl-quant-research",
        name: "Quant Research Team",
        description: "Statistics-first research team wired into the Strategy Research Engine and backtest summaries.",
        scope: "builtin",
        config: {
            market: "EURUSD",
            style: "research",
            entryTimeframe: "H1",
            confirmationTimeframe: "H4",
            contextTimeframe: "D1",
            riskProfile: "balanced",
            behavior: "research-first",
            intents: ["quant", "research", "backtest", "statistics"],
        },
        agentIds: [
            "market-regime",
            "quant-research",
            "strategy-research",
            "technical-analyst",
            "contrarian",
            "risk-manager",
            "chief-analyst",
        ],
        tags: ["quant", "research"],
    },
    {
        id: "tpl-conservative-analysis",
        name: "Conservative Market Analysis Team",
        description: "Slow, evidence-heavy analysis desk. Risk-first behavior with explicit invalidation mapping.",
        scope: "builtin",
        config: {
            market: "XAUUSD",
            style: "swing",
            entryTimeframe: "H1",
            confirmationTimeframe: "H4",
            contextTimeframe: "D1",
            riskProfile: "conservative",
            behavior: "risk-first",
            intents: ["risk", "regime", "technical", "monitoring"],
            behaviorRules: { requireRiskValidation: true, minConsensusConfidence: 0.6 },
        },
        agentIds: [
            "market-regime",
            "technical-analyst",
            "risk-manager",
            "macro-news",
            "contrarian",
            "setup-validator",
            "chief-analyst",
        ],
        tags: ["conservative", "analysis"],
    },
    {
        id: "tpl-strategy-validation",
        name: "Strategy Validation Team",
        description: "Validates candidate strategies and setups against research records, statistics and setup memory.",
        scope: "builtin",
        config: {
            market: "EURUSD",
            style: "research",
            entryTimeframe: "M15",
            confirmationTimeframe: "H1",
            contextTimeframe: "H4",
            riskProfile: "balanced",
            behavior: "research-first",
            intents: ["validation", "setup-validation", "research", "quant"],
            behaviorRules: { requireQuantValidation: true },
        },
        agentIds: [
            "strategy-research",
            "quant-research",
            "setup-validator",
            "technical-analyst",
            "risk-manager",
            "contrarian",
            "chief-analyst",
        ],
        tags: ["validation", "research"],
    },
];

export function getBuiltinTemplate(id: string): TeamTemplate | undefined {
    return BUILTIN_TEAM_TEMPLATES.find((t) => t.id === id);
}
