/**
 * AI Panel Adapter — connects AI modules to Trading Studio UI
 */
import { MarketIntelligenceContext, AIAnalysisResponse } from "./ai/types";
import { analyzeMarket } from "./ai/market-analyst";
import { explainStrategy } from "./ai/strategy-copilot";
import { analyzeBacktest } from "./ai/backtest-analyst";
import { generateStrategyFromPrompt } from "./ai/strategy-generator";

export type AIMode = "market_analyst" | "strategy_copilot" | "backtest_analyst" | "strategy_generator";

export interface AIPanelState {
  open: boolean;
  mode: AIMode;
  loading: boolean;
  result?: AIAnalysisResponse;
  error?: string;
}

export async function handleAIRequest(
  mode: AIMode,
  context?: MarketIntelligenceContext,
  prompt?: string
): Promise<{ result?: AIAnalysisResponse; error?: string }> {
  try {
    switch (mode) {
      case "market_analyst":
        return { result: analyzeMarket(context ?? { symbol: "?", timeframe: "?", timestamp: Date.now(), mode: "historical", limitations: ["No context"] }) };
      case "strategy_copilot":
        return { result: explainStrategy(context?.strategy?.name, 0) };
      case "backtest_analyst":
        return { result: analyzeBacktest(context?.backtest ?? {}) };
      case "strategy_generator":
        const gen = generateStrategyFromPrompt(prompt ?? "Generate a basic test strategy");
        return { result: { summary: "Generated strategy.", observations: [{ type: "fact", text: `Strategy ${gen.definition.name}` }], evidence: [], suggestions: [{ type: "modify", reason: "Generated by AI.", requiresBacktest: true }], limitations: gen.limitations, mode: "historical", contextSymbol: context?.symbol ?? "?", contextTimeframe: context?.timeframe ?? "?", contextTimestamp: Date.now() } };
      default:
        return { error: "Unknown AI mode." };
    }
  } catch (e) {
    return { error: String(e) };
  }
}
