export const RELATION_TYPES = ["DERIVED_FROM", "OBSERVED_IN", "CONTRIBUTES_TO", "TRIGGERED_BY", "CONTAINS", "HAS_LIFECYCLE", "INSTANCE_OF", "BELONGS_TO_PATTERN", "VALIDATED_BY", "GENERATED_FROM", "TESTED_BY", "HAS_OOS_RESULT", "HAS_WALK_FORWARD_RESULT", "HAS_ROBUSTNESS_RESULT", "HAS_MONTE_CARLO_RESULT", "SUPPORTED_BY", "EVIDENCED_BY", "RESULT_OF", "REFERENCES", "PRECEDES", "FOLLOWS", "RELATED_TO",
  // Autonomous Strategy Research Engine (research lineage — additive only).
  "MISSION_GENERATED", "HYPOTHESIS_DERIVED_FROM", "STRATEGY_TESTED_ON", "STRATEGY_SIMILAR_TO",
  "STRATEGY_FAILED_OOS", "STRATEGY_FAILED_WALK_FORWARD", "STRATEGY_SUPPORTED_BY", "STRATEGY_REQUIRES", "STRATEGY_EVOLVED_FROM"];
