/**
 * AI free daily signals — client engine for the popup.
 *
 * Flow: the user picks up to 3 symbols (persisted), presses "Generate daily
 * signals", and the AlgoVault deterministic signal engine produces at most
 * one trade idea per symbol: direction, entry, stop loss and three take-profit
 * targets (TP1 / TP2 / TP3), plus confidence and reasoning. Signals are
 * generated by the SAME engine as the web AI Signals — chart confluence
 * (session levels, daily pivots, VWAP, EMA 9/20, EQH/EQL) + market structure
 * + liquidity + quality filter — so the levels shown in the popup are the
 * ones the chart draws. There is no LLM in this path.
 *
 * Free quota: 3 signals per calendar day.
 *
 * ANTI-RESET DESIGN — why deleting + reinstalling the extension no longer
 * resets the 3 free daily signals:
 *
 * 1. SERVER-SIDE QUOTA (primary). The counter lives on the AlgoVault server
 *    (Firebase), reserved atomically per generation. The client never decides
 *    how many signals it has left.
 * 2. INSTALL IDENTITY THAT SURVIVES REINSTALL. Anonymous (logged-out) users
 *    are keyed by a random install id that the AlgoVault WEBSITE generates
 *    and stores in ITS localStorage (site origin — untouched when the
 *    extension is removed) and mirrors into chrome.storage.sync (rides the
 *    Chrome profile). Deleting the extension destroys chrome.storage.local,
 *    but NOT the site's localStorage nor storage.sync.
 * 3. NOTARIZED LOCAL FALLBACK. If the server is unreachable, the local
 *    day-stamp fallback carries an HMAC signature of (id · day · used) so
 *    editing/deleting the stamp in devtools cannot grant fresh quota — a
 *    tampered stamp falls back to treating the allowance as spent-protected
 *    (deny), never as free.
 */
import { getAISignals, getExtensionDailySignalsState, generateSignalsOnServer } from "@/api/algovault";
import {
  getDailySignalsState, getSelectedSignalSymbols, saveSelectedSignalSymbols,
  getServerInstallId,
} from "@/storage/storage";
import type { EnrichedChartContext } from "@/services/chart-intelligence";
import type { DailySignal } from "@/types";

export const MAX_SIGNAL_SYMBOLS = 3;
export const FREE_DAILY_SIGNAL_LIMIT = 3;

/** localStorage key on the algovault site origin holding the install id. */
export const INSTALL_ID_SITE_STORAGE_KEY = "algovaultExtInstallId";

/* ── symbol selection ─────────────────────────────────────────────────── */

export async function loadSelectedSymbols(): Promise<string[]> {
  return getSelectedSignalSymbols();
}

export async function storeSelectedSymbols(symbols: string[]): Promise<void> {
  const unique = Array.from(new Set(symbols.map((s) => s.trim().toUpperCase()).filter(Boolean)));
  await saveSelectedSignalSymbols(unique.slice(0, MAX_SIGNAL_SYMBOLS));
  // NOTE: intentionally NO server call here. The symbol pick is mirrored by
  // the generation endpoint itself (POST stores the picked symbols), and a
  // generate call from this path would silently CONSUME a free daily signal
  // every time the user added/removed a symbol.
}

/* ── notarized local fallback (offline / server unreachable) ──────────── */

const QUOTA_STAMP_SECRET = "algovault-ext-quota-fallback-v1";

async function hmacInstallStamp(installId: string, day: string, used: number): Promise<string> {
  try {
    const enc = new TextEncoder();
    const key = await crypto.subtle.importKey(
      "raw",
      enc.encode(QUOTA_STAMP_SECRET),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"]
    );
    const sig = await crypto.subtle.sign("HMAC", key, enc.encode(`${installId}:${day}:${used}`));
    return Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, "0")).join("");
  } catch {
    return "unavailable";
  }
}

async function verifyInstallStamp(installId: string, day: string, used: number, stamp: string): Promise<boolean> {
  if (!stamp || stamp === "unavailable") return false;
  return stamp === (await hmacInstallStamp(installId, day, used));
}

function todayStamp(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD (UTC day, matches server)
}

interface LocalQuotaState {
  day: string;
  used: number;
  /** HMAC(installId:day:used) — detects devtools tampering of the stamp. */
  sig?: string;
}

export interface DailyQuota {
  used: number;
  limit: number;
  remaining: number;
  day: string;
  /** Where the authoritative count came from. */
  source: "server" | "local";
}

async function getLocalQuota(): Promise<DailyQuota> {
  const state = await getDailySignalsState();
  const day = todayStamp();
  const s = state as LocalQuotaState;
  if (s.day !== day) return { used: 0, limit: FREE_DAILY_SIGNAL_LIMIT, remaining: FREE_DAILY_SIGNAL_LIMIT, day, source: "local" };

  const installId = await getServerInstallId();
  if (installId) {
    const ok = await verifyInstallStamp(installId, s.day, s.used, s.sig ?? "");
    if (!ok) {
      // Tampered (or pre-notarization) stamp: fail CLOSED for anonymous users.
      return { used: FREE_DAILY_SIGNAL_LIMIT, limit: FREE_DAILY_SIGNAL_LIMIT, remaining: 0, day, source: "local" };
    }
  }
  const used = Math.max(0, Math.min(FREE_DAILY_SIGNAL_LIMIT, s.used));
  return { used, limit: FREE_DAILY_SIGNAL_LIMIT, remaining: Math.max(0, FREE_DAILY_SIGNAL_LIMIT - used), day, source: "local" };
}

/**
 * Authoritative quota: server first (keyed by uid or the durable install id),
 * tamper-resistant local fallback when the server can't be reached.
 */
export async function getQuota(): Promise<DailyQuota> {
  try {
    const state = await getExtensionDailySignalsState();
    if (state) {
      return {
        used: state.quota.used,
        limit: state.quota.limit,
        remaining: state.quota.remaining,
        day: state.quota.day,
        source: "server",
      };
    }
  } catch { /* offline / server error → local fallback */ }
  return getLocalQuota();
}

/* ── signal generation (server engine) ─────────────────────────── */

export interface GenerateOptions {
  symbols: string[];
  /** Unused since the deterministic server engine took over (kept for API compat). */
  contexts?: Map<string, EnrichedChartContext | null>;
  /** Unused since the deterministic server engine took over (kept for API compat). */
  getStructuredContext?: (symbol: string) => string | null;
}

export interface GenerateResult {
  signals: DailySignal[];
  quota: DailyQuota;
  note: string | null;
}

/** Converts a server-stored signal into the popup's DailySignal shape. */
function toDailySignal(s: {
  symbol: string; direction: string; timeframe: string; entry: number; stopLoss: number;
  takeProfit1: number; takeProfit2: number; takeProfit3: number;
  confidence: number; setup: string; reasoning: string; createdAt: number;
  riskReward?: number;
  chartEvidence?: string[];
  chartLevels?: Array<{ kind: string; label: string; price: number }>;
}): DailySignal {
  return {
    id: `ds_${String(s.symbol).toLowerCase()}_${s.createdAt}_${Math.random().toString(36).slice(2, 7)}`,
    symbol: String(s.symbol).toUpperCase(),
    direction: String(s.direction).toUpperCase() === "SELL" ? "SELL" : "BUY",
    timeframe: String(s.timeframe || "M15"),
    entry: Number(s.entry),
    stopLoss: Number(s.stopLoss),
    takeProfit1: Number(s.takeProfit1),
    takeProfit2: Number(s.takeProfit2),
    takeProfit3: Number(s.takeProfit3),
    confidence: Number(s.confidence) || 0,
    setup: String(s.setup ?? ""),
    reasoning: String(s.reasoning ?? ""),
    createdAt: Number(s.createdAt) || Date.now(),
    riskReward: Number.isFinite(Number(s.riskReward)) ? Number(s.riskReward) : undefined,
    chartEvidence: Array.isArray(s.chartEvidence) ? s.chartEvidence.slice(0, 6) : undefined,
    chartLevels: Array.isArray(s.chartLevels) ? s.chartLevels.slice(0, 12) : undefined,
  };
}

/**
 * Generates the daily signals.
 *
 * The AlgoVault server runs the SAME deterministic engine as the web AI
 * Signals (chart confluence + structure + liquidity + quality filter) and
 * stores the result under the user uid / durable install id, so signals
 * survive reinstall. There is no LLM and no offline fallback: without the
 * server there is no OHLC data to analyse, so we refuse rather than fabricate
 * signals. Quota is only consumed when the engine actually returns signals.
 */
export async function generateDailySignals(opts: GenerateOptions): Promise<GenerateResult> {
  const quota = await getQuota();
  const symbols = opts.symbols.slice(0, Math.min(MAX_SIGNAL_SYMBOLS, quota.remaining));

  if (symbols.length === 0) {
    return {
      signals: [],
      quota,
      note: quota.remaining === 0 ? "Daily free limit reached — come back tomorrow." : "Pick at least one symbol first.",
    };
  }

  try {
    // Context payloads are no longer needed — the engine fetches the same
    // canonical OHLC feed the chart uses. Parameters kept for API compat.
    void opts.contexts;
    void opts.getStructuredContext;
    const serverResult = await generateSignalsOnServer(symbols, "");
    if (serverResult.success) {
      const serverSignals = (serverResult.signals ?? []).map(toDailySignal);
      const nextQuota = await getQuota();
      return {
        signals: serverSignals,
        quota: nextQuota,
        note: serverSignals.length === 0 ? (serverResult.note ?? "No valid setups right now — try again later or change symbols.") : null,
      };
    }
    return {
      signals: [],
      quota,
      note: serverResult.note ?? "Signal engine unavailable — try again shortly.",
    };
  } catch (err) {
    // apiPost throws with the server's own message (e.g. the 429 daily-limit
    // text) — surface it verbatim instead of a misleading network error.
    const msg = err instanceof Error && err.message && !/API error \d+/.test(err.message)
      ? err.message
      : "Could not reach the signal engine. Check your connection and try again — your daily allowance was not used.";
    return {
      signals: [],
      quota,
      note: msg,
    };
  }
}

/* ── history (server signals, best effort) ────────────────────────────── */

export interface ServerSignalSummary {
  signals: Awaited<ReturnType<typeof getAISignals>>;
  error: string | null;
}

export async function loadServerSignals(symbols: string[]): Promise<ServerSignalSummary> {
  try {
    const all: Awaited<ReturnType<typeof getAISignals>> = [];
    for (const symbol of symbols) {
      const list = await getAISignals(symbol, 10);
      all.push(...list);
    }
    all.sort((a, b) => b.createdAt - a.createdAt);
    return { signals: all.slice(0, 12), error: null };
  } catch (err) {
    return { signals: [], error: err instanceof Error ? err.message : "Failed to load signals" };
  }
}
