/**
 * Marketing Agent — SVML translator (§11, §12).
 *
 * The editable system of record is the `CompositionDocument` JSON. This module
 * renders it into Hypit Author Source (`.svml`) and a Run Source (`.svrun`)
 * so the composition can be checked, planned, built and re-built by the Hypit
 * CLI.
 *
 * IMPORTANT: every generated source is validated with `hypit check` BEFORE a
 * build is submitted (see `HypitMarketingProvider.render`). If the installed
 * Hypit version speaks a different SVML dialect, the run fails closed with the
 * real diagnostic instead of shipping an unvalidated artifact.
 *
 * Dialect: `@hypit/markup@1` / `@hypit/run-markup@1` (Hypit ≥ EXPECTED version).
 *
 * Pure module: no I/O.
 */

import type { CompositionDocument, MotionLayer, TimelineClip } from "../provider";

const XML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&apos;",
};

export function esc(value: string): string {
  return String(value).replace(/[&<>"']/g, (c) => XML_ESCAPES[c] ?? c);
}

/** Duration in milliseconds → Hypit time attribute (`1200ms`). */
function ms(value: number): string {
  return `${Math.max(0, Math.round(value))}ms`;
}

const CANVAS_SIZES: Record<string, { width: number; height: number }> = {
  "9:16": { width: 1080, height: 1920 },
  "1:1": { width: 1080, height: 1080 },
  "4:5": { width: 1080, height: 1350 },
  "16:9": { width: 1920, height: 1080 },
};

export function canvasFor(aspectRatio: string): { width: number; height: number } {
  return CANVAS_SIZES[aspectRatio] ?? CANVAS_SIZES["9:16"];
}

function uniqueAssets(clips: TimelineClip[]): { id: string; ref: string; type: string }[] {
  const seen = new Map<string, { id: string; ref: string; type: string }>();
  for (const clip of clips) {
    if (!clip.source.ref) continue;
    const id = `src_${clip.source.ref.replace(/[^A-Za-z0-9]+/g, "_").slice(0, 48)}`;
    if (!seen.has(id)) seen.set(id, { id, ref: clip.source.ref, type: clip.source.type });
  }
  return Array.from(seen.values());
}

function assetElement(a: { id: string; ref: string; type: string }): string {
  const src = a.ref.startsWith("/") || a.ref.startsWith("./") ? a.ref : `./assets/${a.ref}`;
  if (a.type === "capture" || a.type === "asset") {
    const ext = src.split(".").pop()?.toLowerCase() ?? "";
    if (["mp4", "mov", "webm"].includes(ext)) return `<asset:Video id="${esc(a.id)}" src="${esc(src)}"/>`;
    return `<asset:Image id="${esc(a.id)}" src="${esc(src)}"/>`;
  }
  if (a.type === "chart") return `<asset:Image id="${esc(a.id)}" src="${esc(src)}"/>`;
  return `<asset:Image id="${esc(a.id)}" src="${esc(src)}"/>`;
}

function clipKindComment(clip: TimelineClip): string {
  return `${clip.kind} ${clip.startMs}ms–${clip.endMs}ms${clip.text ? ` — ${clip.text.slice(0, 60)}` : ""}`;
}

function motionElement(layer: MotionLayer): string {
  const attrs = [
    `id="${esc(layer.id)}"`,
    `clip="${esc(layer.clipId)}"`,
    `from="${ms(layer.from)}"`,
    `to="${ms(layer.to)}"`,
    layer.label ? `label="${esc(layer.label)}"` : "",
    layer.target ? `target="${esc(layer.target)}"` : "",
    layer.style ? `recipe="${esc(layer.style)}"` : "",
  ].filter(Boolean);
  return `<mg:Overlay ${attrs.join(" ")}/>`;
}

/**
 * Render the Author Source (`.svml`) for one composition.
 * Deterministic: the same document always produces byte-identical source.
 */
export function renderSvml(doc: CompositionDocument, options?: { captureRefs?: string[] }): string {
  const canvas = canvasFor(doc.aspectRatio);
  const assets = uniqueAssets(doc.timeline);
  const lines: string[] = [];

  lines.push(`<?svml using="@hypit/markup@1"?>`);
  lines.push(`<svml>`);
  lines.push(`<import from="@hypit/script@1"/>`);
  lines.push(`<import as="asset" from="@hypit/media@1"/>`);
  lines.push(`<import as="text" from="@hypit/text@1"/>`);
  lines.push(`<import as="time" from="@hypit/timeline-author@1"/>`);
  lines.push(`<import as="media-track" from="@hypit/media-track@1"/>`);
  lines.push(`<import as="audio-track" from="@hypit/audio-track@1"/>`);
  lines.push(`<import as="caption" from="@hypit/caption@1"/>`);
  lines.push(`<import as="space" from="@hypit/spatial@1"/>`);
  lines.push(`<import as="program" from="@hypit/program-space@1"/>`);
  lines.push(`<import as="render" from="@hypit/render-hyperframes@1"/>`);
  lines.push(`<!-- Generated by the AlgoVault Marketing Agent. Editable source of truth is the composition JSON. -->`);

  // ── Narration script (drives word-level captions) ──────────────────────────
  const narration = doc.timeline.filter((c) => c.text && (c.kind === "hook" || c.kind === "demo" || c.kind === "benefit" || c.kind === "cta"));
  if (narration.length > 0) {
    lines.push(`<script id="story">`);
    narration.forEach((clip, i) => {
      lines.push(`<scene${i + 1}>`);
      lines.push(`<NARRATOR>${esc(clip.text ?? "")}</NARRATOR>`);
      lines.push(`</scene${i + 1}>`);
    });
    lines.push(`</script>`);
  }

  // ── Media ─────────────────────────────────────────────────────────────────
  assets.forEach((a) => lines.push(assetElement(a)));
  if (doc.audio.voice) lines.push(`<asset:Audio id="voice" src="${esc(doc.audio.voice)}"/>`);
  if (doc.audio.music) lines.push(`<asset:Audio id="music" src="${esc(doc.audio.music)}"/>`);

  // ── Canvas / clock ────────────────────────────────────────────────────────
  lines.push(`<space:Canvas id="canvas" width="${canvas.width}" height="${canvas.height}"/>`);
  lines.push(`<program:Clock id="clock" frame-rate="30"/>`);

  // ── Timeline ──────────────────────────────────────────────────────────────
  lines.push(`<time:Timeline id="main" clock={clock}>`);
  for (const clip of doc.timeline) {
    lines.push(`  <!-- ${esc(clipKindComment(clip))} -->`);
    const anchorFrame = `<space:Frame id="frame_${esc(clip.id)}" within={canvas} left="0%" top="0%" right="100%" bottom="100%"/>`;
    lines.push(`  ${anchorFrame}`);
    const sourceRef = clip.source.ref
      ? assets.find((a) => a.id === `src_${clip.source.ref?.replace(/[^A-Za-z0-9]+/g, "_").slice(0, 48)}`)
      : undefined;
    const source = sourceRef ? ` source={${sourceRef.id}}` : "";
    const text = clip.text ? ` text="${esc(clip.text)}"` : "";
    lines.push(
      `  <time:Item id="${esc(clip.id)}"${source} start="${ms(clip.startMs)}" end="${ms(clip.endMs)}" anchor="${clip.anchor}"${text}/>`
    );
  }
  lines.push(`</time:Timeline>`);

  // ── Captions ──────────────────────────────────────────────────────────────
  if (doc.captions.cues.length > 0) {
    lines.push(`<caption:Track id="captions" timeline={main} style="${esc(doc.captions.style)}" language="${esc(doc.language)}">`);
    for (const cue of doc.captions.cues) {
      const emphasis = cue.emphasis?.length ? ` emphasis="${esc(cue.emphasis.join(","))}"` : "";
      lines.push(`  <caption:Cue start="${ms(cue.startMs)}" end="${ms(cue.endMs)}"${emphasis}>${esc(cue.text)}</caption:Cue>`);
    }
    lines.push(`</caption:Track>`);
  }

  // ── Audio ─────────────────────────────────────────────────────────────────
  if (doc.audio.voice) {
    lines.push(`<audio-track:Track id="voice-track" timeline={main}>`);
    // Ducking names the logical track being ducked, not its file — the music
    // track below is id="music-track", ducked under the voice (§18).
    lines.push(`  <audio-track:Item source={voice} during="program"${doc.audio.ducking && doc.audio.music ? ` ducking="music"` : ""}/>`);
    lines.push(`</audio-track:Track>`);
  }
  if (doc.audio.music) {
    lines.push(`<audio-track:Track id="music-track" timeline={main}>`);
    lines.push(`  <audio-track:Item source={music} during="program" gain="${doc.audio.voice ? "0.18" : "0.6"}" fade-in="300ms" fade-out="600ms"/>`);
    lines.push(`</audio-track:Track>`);
  }

  // ── Motion graphics ───────────────────────────────────────────────────────
  if (doc.motion.length > 0) {
    lines.push(`<mg:Layer id="motion" timeline={main} canvas={canvas}>`);
    doc.motion.forEach((m) => lines.push(`  ${motionElement(m)}`));
    lines.push(`</mg:Layer>`);
  }

  // ── Branding / labels ─────────────────────────────────────────────────────
  if (doc.branding.logo) {
    lines.push(`<brand:Logo id="logo" src="${esc(doc.branding.logo)}" anchor="top-right" from="0ms" to="${ms(doc.durationSec * 1000)}"/>`);
  }
  if (doc.demoLabel) {
    lines.push(`<label:Watermark id="demo-label" text="${esc(doc.demoLabel)}" anchor="bottom-right" opacity="0.7"/>`);
  }
  if (doc.disclaimer) {
    lines.push(`<label:Disclosure id="disclaimer" text="${esc(doc.disclaimer)}" anchor="bottom" from="${ms(Math.max(0, doc.durationSec * 1000 - 6000))}"/>`);
  }

  // ── Render target ─────────────────────────────────────────────────────────
  lines.push(`<render:Output id="final.video" timeline={main} canvas={canvas} codec="h264" frame-rate="30"/>`);

  lines.push(`</svml>`);
  return lines.join("\n");
}

/**
 * Render the Run Source (`.svrun`) that demands the finished video plus a
 * caption track. Explicit reuse of a previous build is expressed by
 * `reuseBuild` — Hypit never infers reuse implicitly.
 */
export function renderSvrun(input: {
  authorSource: string;
  reuse?: { buildId: string; output: string; candidateId: string }[];
}): string {
  const lines: string[] = [];
  lines.push(`<?svml using="@hypit/run-markup@1"?>`);
  lines.push(`<svrun version="1">`);
  lines.push(`  <author source="${esc(input.authorSource)}"/>`);
  lines.push(`  <target output="final.video"/>`);
  lines.push(`  <target output="captions.track"/>`);
  for (const reuse of input.reuse ?? []) {
    lines.push(`  <build-record id="${esc(reuse.candidateId)}" build="${esc(reuse.buildId)}" output="${esc(reuse.output)}"/>`);
    lines.push(`  <satisfy output="${esc(reuse.output)}" candidate="${esc(reuse.candidateId)}"/>`);
  }
  lines.push(`</svrun>`);
  return lines.join("\n");
}

/** Aspect-ratio recomposition instructions (§19) — never a stretch/crop. */
export function recompositionNotes(aspectRatio: string): string {
  switch (aspectRatio) {
    case "9:16":
      return "Vertical: enlarge the product capture, centre-weight captions in the lower third, keep UI safe zones clear.";
    case "16:9":
      return "Horizontal: widen the capture frame, move captions to a bottom bar, add breathing room either side.";
    case "1:1":
      return "Square: centre-weight the capture, tighten captions, trim horizontal chrome.";
    case "4:5":
      return "Portrait feed: centre the capture, keep captions above the platform UI overlay.";
    default:
      return "Recompose for the target aspect ratio; never stretch or crop the source.";
  }
}
