import {
    AIProvider,
    StrategyNarrative,
    StrategyNarrativeInput,
    AnalysisSummary,
    AnalysisSummaryInput,
    AIChatRequest,
    AIResponse,
    AIModel,
} from "./types";
import { buildFallbackNarrative } from "./validate";

// ─────────────────────────────────────────────────────────────────────────────
// Local heuristic provider — deterministic offline fallback.
//
// Produces response narratives from REAL statistics and conditions computed by
// application engines. Keeps all features fully functional with zero external
// API dependencies or when cloud free quotas are temporarily rate limited.
// ─────────────────────────────────────────────────────────────────────────────

export class LocalStrategyAIProvider implements AIProvider {
    readonly id = "local-heuristic";
    readonly name = "Local Strategy Engine (Offline)";

    isAvailable(): boolean {
        return true;
    }

    available(): boolean {
        return true;
    }

    async getModels(): Promise<AIModel[]> {
        return [
            {
                id: "local-heuristic",
                name: "Local Deterministic Heuristic Engine",
                provider: "local-heuristic",
                free: true,
                confirmedFree: true,
                enabled: true,
                capabilities: { text: true, structuredOutput: true },
            },
        ];
    }

    async chat(request: AIChatRequest): Promise<AIResponse> {
        const lastMsg = [...request.messages].reverse().find((m) => m.role === "user")?.content || "";
        const systemPrompt = request.systemPrompt || "";

        let reply: string;
        if (systemPrompt.includes("JSON") || request.responseFormat === "json_object") {
            reply = JSON.stringify({
                status: "success",
                message: "Processed via local heuristic gateway",
                summary: lastMsg.slice(0, 200),
            });
        } else if (lastMsg.toLowerCase().includes("pine") || lastMsg.toLowerCase().includes("script")) {
            reply = `// Pine Script v5 generated via AI Gateway\n//@version=5\nindicator("AI Strategy Indicator", overlay=true)\nplot(ta.sma(close, 20), color=color.blue)`;
        } else {
            reply = [
                "⚠ Cloud AI providers are currently unavailable, so this answer was generated by the local deterministic engine from the structured chart context in this conversation.",
                "",
                "The relevant market facts are contained in the TradingView Context and Market Data blocks above (symbol, timeframe, price, indicators, trend, structure, volatility, and key levels).",
                "For a full AI narrative, verify that at least one free AI provider key is configured on the AlgoVault server, then retry.",
            ].join("\n");
        }

        return {
            success: true,
            provider: this.id,
            model: "local-heuristic",
            content: reply,
            finishReason: "stop",
            truncated: false,
        };
    }

    async generateText(prompt: string, systemPrompt?: string): Promise<string> {
        const res = await this.chat({
            messages: [{ role: "user", content: prompt }],
            systemPrompt,
        });
        return res.content;
    }

    async chatCompletion(messages: Array<{ role: "system" | "user" | "assistant"; content: string }>, systemPrompt?: string): Promise<string> {
        const res = await this.chat({
            messages,
            systemPrompt,
        });
        return res.content;
    }

    async generateStructured<T>(prompt: string, _schemaDescription?: string, systemPrompt?: string): Promise<T> {
        const res = await this.chat({
            messages: [{ role: "user", content: prompt }],
            systemPrompt,
            responseFormat: "json_object",
        });
        try {
            return JSON.parse(res.content) as T;
        } catch {
            return { status: "success", message: res.content } as unknown as T;
        }
    }

    private makeWhy(input: StrategyNarrativeInput): string {
        const s = input.stats;
        const parts: string[] = [];
        parts.push(input.patternName);
        if (s.occurrences) {
            parts.push(`found ${s.occurrences} times in the ${input.period} window on ${input.timeframe}`);
            if (s.winRate !== null) parts.push(`winning ${s.winRate.toFixed(1)}% of the time`);
            if (s.profitFactor !== null) parts.push(`profit factor ${s.profitFactor.toFixed(2)}`);
            if (s.averageR !== null) parts.push(`average outcome ${s.averageR >= 0 ? "+" : ""}${s.averageR.toFixed(2)}R`);
            if (s.maxLossStreak !== null) parts.push(`worst losing streak ${s.maxLossStreak}`);
        } else {
            parts.push("it is the strongest pattern observed in the available history");
        }
        return parts.join(", ") + ".";
    }

    async describeStrategy(input: StrategyNarrativeInput): Promise<StrategyNarrative> {
        const fallback = buildFallbackNarrative(input);
        const dir = input.direction === "long" ? "Long" : "Short";
        const s = input.stats;
        const statsText = s.occurrences
            ? `${s.occurrences} occurrences · ${s.winRate?.toFixed(1)}% win rate · avg ${s.averageR?.toFixed(2)}R · max DD ${s.maxDrawdownPct?.toFixed(1)}% · PF ${s.profitFactor?.toFixed(2)}`
            : "insufficient occurrences for statistics";

        return {
            name: fallback.name,
            description: `${dir} strategy for ${input.asset}. Entries follow ${input.patternName.toLowerCase()} on the ${input.timeframe} setup, using ${input.hierarchy.macro}/${input.hierarchy.structure}/${input.hierarchy.entry} for the macro/structure/entry confirmation stack. Filters limit activity to ${input.bestSession} hours.`,
            why: this.makeWhy(input),
            risks: `- Relies on the ${input.timeframe} formation completing; false starts are possible.\n- Worst stats: ${statsText}.\n- Degrades when ${input.volatility} volatility persists over several sessions without a clean breakout or sweep.`,
            bestRegimes: input.regime,
            weakRegimes:
                input.regime === "ranging" || input.regime === "low_volatility"
                    ? "Extended ranging conditions and low-impact holiday sessions."
                    : "Choppy ranging conditions, low-volatility sessions, and high-impact news windows.",
            generatedBy: this.id,
        };
    }

    async summarizeAnalysis(input: AnalysisSummaryInput): Promise<AnalysisSummary> {
        const avgRLabel = input.averageR !== null ? `${input.averageR >= 0 ? "+" : ""}${input.averageR.toFixed(2)}R average` : "no average R yet";
        return {
            summary: `${input.asset} on ${input.timeframe} is ${input.trend} with ${input.volatility} volatility. The regime is ${input.regime}. The strongest session is ${input.bestSession} and the best day is ${input.bestDay}. The most successful setup is ${input.strongestSetup}, with ${avgRLabel}.`,
            generatedBy: this.id,
        };
    }
}

export { LocalStrategyAIProvider as LocalHeuristicProvider };