import { AgentContract, AgentRole } from "./types";

export const BUILT_IN_AGENTS: AgentContract[] = [
    {
        id: "market-scout",
        name: "Market Scout",
        version: "1.0.0",
        role: "scout",
        description: "Detects market events, unusual conditions, and candidate opportunities across configured instruments. Does NOT make final decisions.",
        capabilities: ["event_detection", "condition_scanning", "opportunity_flagging"],
        requiredPermissions: ["market_data"],
        inputSchema: { symbols: "string[]", timeframe: "string" },
        outputSchema: { findings: "AgentFinding[]", candidateCount: "number" },
        systemInstructions: "You are a Market Scout. Scan market snapshots for unusual conditions. Flag candidates — never decide.",
        tools: ["market_snapshot", "volatility_check", "structure_detect"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "market-context",
        name: "Market Context",
        version: "1.0.0",
        role: "context",
        description: "Analyses market regime, volatility, structure, momentum, timeframe context and session context.",
        capabilities: ["regime_detection", "volatility_assessment", "structure_analysis", "session_context"],
        requiredPermissions: ["market_data"],
        inputSchema: { marketSnapshot: "Record<string, unknown>" },
        outputSchema: { regime: "string", volatility: "string", structureCount: "number" },
        systemInstructions: "You describe the current market context from measured data only.",
        tools: ["market_snapshot", "regime_classifier"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: true, minConfidence: 0 },
        status: "active",
    },
    {
        id: "strategy-matcher",
        name: "Strategy Matcher",
        version: "1.0.0",
        role: "strategy-matcher",
        description: "Compares current conditions with user-selected strategies and historical setup fingerprints. Identifies similarities and mismatches. Does NOT guarantee future performance.",
        capabilities: ["similarity_matching", "fingerprint_comparison", "condition_alignment"],
        requiredPermissions: ["strategy_data", "market_data", "historical_data"],
        inputSchema: { currentConditions: "Record<string, unknown>", history: "Trade[]" },
        outputSchema: { similarCount: "number", matchRatio: "number" },
        systemInstructions: "Compare current market conditions against recorded historical setups. Describe similarity — never predict.",
        tools: ["historical_trades", "setup_fingerprints"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 15000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "risk-analyst",
        name: "Risk Analyst",
        version: "1.0.0",
        role: "risk",
        description: "Assesses account exposure, position concentration, configured risk limits, correlated exposure, drawdown context and user-defined constraints. Factual and data-driven.",
        capabilities: ["exposure_assessment", "concentration_analysis", "limit_checking", "drawdown_context"],
        requiredPermissions: ["portfolio_data", "risk_data", "trading_history"],
        inputSchema: { riskContext: "RiskContext", limits: "Record<string, number>" },
        outputSchema: { drawdownPercent: "number", exposureRatio: "number", riskFlags: "string[]" },
        systemInstructions: "Assess risk factually from measured data. Never request actions — report measured numbers.",
        tools: ["portfolio_data", "risk_limits", "position_data"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: true, minConfidence: 0 },
        status: "active",
    },
    {
        id: "news-agent",
        name: "News / Event Agent",
        version: "1.0.0",
        role: "news",
        description: "Surfaces relevant economic events, scheduled events, available news context and potential market relevance. Never claims certainty about event impact.",
        capabilities: ["event_detection", "calendar_check", "impact_assessment"],
        requiredPermissions: ["news_data"],
        inputSchema: { events: "CalendarEvent[]", symbols: "string[]" },
        outputSchema: { eventCount: "number", highImpactCount: "number" },
        systemInstructions: "Report what the calendar says. Never claim certainty about market impact.",
        tools: ["economic_calendar", "event_database"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 15000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "pattern-discovery",
        name: "Pattern Discovery",
        version: "1.0.0",
        role: "pattern-discovery",
        description: "Discovers recurring patterns from historical data: setup patterns, behavioral patterns, strategy conditions, recurring market environments.",
        capabilities: ["statistical_analysis", "pattern_recognition", "session_profiling"],
        requiredPermissions: ["historical_data", "trading_history"],
        inputSchema: { trades: "Trade[]" },
        outputSchema: { patterns: "Pattern[]", maxLossStreak: "number" },
        systemInstructions: "Discover descriptive patterns from recorded trades. Label all findings as observations, never predictions.",
        tools: ["historical_trades", "statistical_engine"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 15000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "critic",
        name: "Critic",
        version: "1.0.0",
        role: "critic",
        description: "REQUIRED component. Actively challenges previous analysis: What could be wrong? What evidence is missing? Are signals contradictory? Is data stale? Is there overfitting?",
        capabilities: ["contradiction_detection", "evidence_audit", "bias_detection", "confidence_adjustment"],
        requiredPermissions: ["market_data", "historical_data"],
        inputSchema: { priorOutputs: "Record<string, AgentOutput>" },
        outputSchema: { majorConflict: "boolean", confidenceAdjustment: "number", criticism: "string[]" },
        systemInstructions: "Challenge every conclusion. Find contradictions, missing evidence, bias, and overfitting. Never agree without scrutiny.",
        tools: ["prior_outputs", "evidence_checker", "data_freshness"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 15000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "verification",
        name: "Verification",
        version: "1.0.0",
        role: "verification",
        description: "Checks data consistency, schema validity, stale data, missing fields, conflicting agent outputs, and unsupported claims. If verification fails, workflow must not produce a high-confidence result.",
        capabilities: ["schema_check", "consistency_check", "claim_validation", "freshness_check"],
        requiredPermissions: ["market_data"],
        inputSchema: { priorOutputs: "Record<string, AgentOutput>" },
        outputSchema: { passed: "boolean", problems: "number", warnings: "number" },
        systemInstructions: "Verify every prior output against the agent contract. Flag unsupported claims and missing evidence.",
        tools: ["output_validator", "claim_checker", "evidence_tracker"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: true, minConfidence: 0 },
        status: "active",
    },
    {
        id: "synthesis",
        name: "Synthesis",
        version: "1.0.0",
        role: "synthesis",
        description: "Produces the final structured intelligence. Summarises situation, distinguishes facts from inference, includes uncertainty, identifies conflicts, produces final output, and decides whether notification is warranted.",
        capabilities: ["synthesis", "fact_inference_separation", "notification_decision", "evidence_strength"],
        requiredPermissions: ["market_data", "notifications"],
        inputSchema: { allOutputs: "Record<string, AgentOutput>", criticOutput: "AgentOutput", verifyOutput: "AgentOutput" },
        outputSchema: { evidenceStrength: "string", facts: "string[]", notify: "object" },
        systemInstructions: "Synthesise all prior outputs. Do NOT blindly follow any agent. Decide independently whether notification is warranted.",
        tools: ["all_outputs", "critic_verdict", "verdict_result", "notification_gateway"],
        modelConfiguration: { poweredBy: "hybrid", provider: "gemini", model: "gemini-2.5-flash", temperature: 0.1, maxTokens: 2000, responseFormat: "json_object" },
        timeoutMs: 20000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: true, minConfidence: 0 },
        status: "active",
    },
    {
        id: "notification",
        name: "Notification",
        version: "1.0.0",
        role: "notification",
        description: "Transforms the final structured result into the user's configured channels: In-App, Push, Telegram, Discord, Email, Webhook.",
        capabilities: ["channel_delivery", "preference_check", "deduplication", "cooldown_check"],
        requiredPermissions: ["notifications", "telegram", "discord", "webhook"],
        inputSchema: { finalOutput: "WorkflowFinalOutput", channels: "string[]" },
        outputSchema: { delivered: "boolean", channels: "string[]" },
        systemInstructions: "Deliver the structured result through the user's configured channels. Respect preferences, quiet hours, cooldown, and severity.",
        tools: ["notify_user", "preference_check", "dedup_check"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 30000,
        retryPolicy: { maxRetries: 1, backoffMs: 5000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "volatility-agent",
        name: "Volatility Agent",
        version: "1.0.0",
        role: "volatility",
        description: "Analyses volatility expansion and abnormal volatility conditions. Parallel-capable.",
        capabilities: ["volatility_expansion", "extreme_condition_detection"],
        requiredPermissions: ["market_data"],
        inputSchema: { marketSnapshot: "Record<string, unknown>" },
        outputSchema: { volatilityState: "string", rangeExpansion: "number" },
        systemInstructions: "Analyse volatility data. Report measured values.",
        tools: ["volatility_analyzer"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
    {
        id: "structure-agent",
        name: "Structure Agent",
        version: "1.0.0",
        role: "structure",
        description: "Analyses market structure and alignment. Parallel-capable.",
        capabilities: ["structure_detection", "alignment_check"],
        requiredPermissions: ["market_data"],
        inputSchema: { marketSnapshot: "Record<string, unknown>" },
        outputSchema: { structureCount: "number", aligned: "boolean" },
        systemInstructions: "Analyse market structure events. Report measured counts.",
        tools: ["structure_analyzer"],
        modelConfiguration: { poweredBy: "deterministic" },
        timeoutMs: 10000,
        retryPolicy: { maxRetries: 2, backoffMs: 1000 },
        validationRules: { failOnError: false, minConfidence: 0 },
        status: "active",
    },
];

export const AGENT_BY_ID: Record<string, AgentContract> = BUILT_IN_AGENTS.reduce(
    (acc, a) => { acc[a.id] = a; return acc; },
    {} as Record<string, AgentContract>
);

/**
 * Runtime registry for domain agents (e.g. the Growth marketing pipeline).
 * Domain modules call `registerAgentContract` at import time so workflow
 * definitions can reference their agents through the same catalog lookup.
 */
export const REGISTRY_AGENTS: AgentContract[] = [];

export function registerAgentContract(agent: AgentContract): void {
    const index = REGISTRY_AGENTS.findIndex((a) => a.id === agent.id);
    if (index >= 0) REGISTRY_AGENTS[index] = agent;
    else REGISTRY_AGENTS.push(agent);
    AGENT_BY_ID[agent.id] = agent;
}

export function getAgent(id: string): AgentContract | undefined {
    return AGENT_BY_ID[id];
}

export function getActiveAgents(): AgentContract[] {
    return [...BUILT_IN_AGENTS, ...REGISTRY_AGENTS].filter((a) => a.status === "active" || a.status === "testing");
}

export const AGENT_ROLE_LABELS: Record<AgentRole, string> = {
    scout: "Market Scout",
    context: "Market Context",
    "strategy-matcher": "Strategy Matcher",
    risk: "Risk Analyst",
    news: "News / Event",
    "pattern-discovery": "Pattern Discovery",
    structure: "Structure",
    volatility: "Volatility",
    critic: "Critic",
    verification: "Verification",
    synthesis: "Synthesis",
    notification: "Notification",
    custom: "Custom",
};
