/** Marketing Content Factory — 15 agent contracts.
 *
 * Mirrors `lib/growth/agents/contracts.ts`: each contract is
 * registered via `registerAgentContract` so the workflow engine
 * can resolve them.
 */

import { AgentContract } from "@/lib/agents/types";
import { registerAgentContract } from "@/lib/agents/catalog";

const HYBRID = { poweredBy: "hybrid" as const, provider: undefined, model: undefined, temperature: 0.3, maxTokens: 1200, responseFormat: "text" as const };
const DETERMINISTIC = { poweredBy: "deterministic" as const };
const RETRY = { maxRetries: 2, backoffMs: 1000 };

export const MARKETING_AGENT_IDS = {
  concept: "marketing-concept",
  research: "marketing-research",
  script: "marketing-script",
  copy: "marketing-copy",
  template: "marketing-template",
  variation: "marketing-variation",
  seo: "marketing-seo",
  captions: "marketing-captions",
  visuals: "marketing-visuals",
  market_visuals: "marketing-market-visuals",
  voiceover: "marketing-voiceover",
  compose: "marketing-compose",
  thumbnail: "marketing-thumbnail",
  compliance: "marketing-compliance",
  publish: "marketing-publish",
} as const;

export const MARKETING_AGENT_CONTRACTS: AgentContract[] = [
  {
    id: MARKETING_AGENT_IDS.concept,
    name: "Concept Agent",
    version: "1.0.0",
    role: "custom",
    description: "Turns a feature/objective into a concept brief (hook, angle, CTA).",
    capabilities: ["concept_brief", "hook_generation"],
    requiredPermissions: [],
    inputSchema: { feature: "string", audience: "string", objective: "string" },
    outputSchema: { hook: "string", angle: "string", cta: "string" },
    systemInstructions: "Be factual; never guarantee returns.",
    tools: ["concept_templates"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.research,
    name: "Research Agent",
    version: "1.0.0",
    role: "custom",
    description: "Produces a research brief for the concept.",
    capabilities: ["market_research", "topic_research"],
    requiredPermissions: [],
    inputSchema: { topic: "string", objective: "string" },
    outputSchema: { brief: "string", sources: "string[]" },
    systemInstructions: "Never invent data points or performance figures.",
    tools: ["research_brief"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 15000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.script,
    name: "Script Agent",
    version: "1.0.0",
    role: "custom",
    description: "Turns the concept + research into a multi-scene video script.",
    capabilities: ["script_generation", "scene_sequencing"],
    requiredPermissions: [],
    inputSchema: { hook: "string", cta: "string", angle: "string", durationSec: "number", aspectRatio: "string" },
    outputSchema: { script: "Script" },
    systemInstructions: "Include a trading risk disclosure on trading-related content.",
    tools: ["script_builder"],
    modelConfiguration: HYBRID,
    timeoutMs: 30000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.copy,
    name: "Copy Agent",
    version: "1.0.0",
    role: "custom",
    description: "Produces per-channel copy variants from the script.",
    capabilities: ["copywriting", "channel_adaptation"],
    requiredPermissions: [],
    inputSchema: { script: "Script", channels: "string[]" },
    outputSchema: { copies: "Record<string, string>" },
    systemInstructions: "Keep claims honest; retain the risk disclosure.",
    tools: ["copy_variants"],
    modelConfiguration: HYBRID,
    timeoutMs: 20000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.4 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.template,
    name: "Template Agent",
    version: "1.0.0",
    role: "custom",
    description: "Applies a data-driven content template (10 types) to the copy.",
    capabilities: ["template_application"],
    requiredPermissions: [],
    inputSchema: { copy: "string", templateId: "string" },
    outputSchema: { templated: "string", appliedTemplate: "string" },
    systemInstructions: "Use the template structure; never invent missing fields.",
    tools: ["template_engine"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.variation,
    name: "Variation Agent",
    version: "1.0.0",
    role: "custom",
    description: "Generates cost-controlled, deduplicated per-stage variants.",
    capabilities: ["variation_generation", "dedup"],
    requiredPermissions: [],
    inputSchema: { stage: "string", kind: "string", seed: "string" },
    outputSchema: { variants: "string[]" },
    systemInstructions: "Respect the cost caps and never fabricate AI enhancements.",
    tools: ["variation_engine"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.seo,
    name: "SEO Agent",
    version: "1.0.0",
    role: "custom",
    description: "Produces SEO metadata and checks draft structure.",
    capabilities: ["seo_metadata", "structure_check"],
    requiredPermissions: [],
    inputSchema: { draft: "string", title: "string" },
    outputSchema: { seoTitle: "string", metaDescription: "string", slug: "string", keywords: "string[]" },
    systemInstructions: "Be honest; never promise rankings.",
    tools: ["seo_checklist"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.2 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.captions,
    name: "Captions Agent",
    version: "1.0.0",
    role: "custom",
    description: "Generates caption cues (SRT) for client-side players.",
    capabilities: ["caption_generation"],
    requiredPermissions: [],
    inputSchema: { script: "Script", voiceoverDurationMs: "number" },
    outputSchema: { cues: "CaptionCue[]", srt: "string" },
    systemInstructions: "Be deterministic; never burn captions (filter unavailable).",
    tools: ["caption_builder"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.visuals,
    name: "Visuals Agent",
    version: "1.0.0",
    role: "custom",
    description: "Selects and maps AlgoVault assets per scene.",
    capabilities: ["asset_selection", "scene_mapping"],
    requiredPermissions: [],
    inputSchema: { script: "Script", preferredSources: "string[]" },
    outputSchema: { assets: "MediaAsset[]", missing: "string[]" },
    systemInstructions: "Use only curated AlgoVault assets; never invent URLs.",
    tools: ["asset_library"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.market_visuals,
    name: "Market Visuals Agent",
    version: "1.0.0",
    role: "custom",
    description: "Generates real-candle SVG sparklines rasterized via qlmanage.",
    capabilities: ["market_visuals", "sparkline"],
    requiredPermissions: [],
    inputSchema: { symbol: "string", timeframe: "string" },
    outputSchema: { visualId: "string", url: "string" },
    systemInstructions: "Only use live market data; fail honestly when unavailable.",
    tools: ["market_chart"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 15000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.voiceover,
    name: "Voiceover Agent",
    version: "1.0.0",
    role: "custom",
    description: "Produces TTS audio via local say → ffmpeg pipeline.",
    capabilities: ["voiceover"],
    requiredPermissions: [],
    inputSchema: { script: "Script", voice: "string" },
    outputSchema: { audio: "MediaAsset" },
    systemInstructions: "Never claim AI-voice success when TTS is unavailable.",
    tools: ["tts_local"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 30000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.compose,
    name: "Compose Agent",
    version: "1.0.0",
    role: "custom",
    description: "Assembles the final video via FFmpeg (Ken Burns, fade, logo overlay).",
    capabilities: ["compose_video"],
    requiredPermissions: [],
    inputSchema: { script: "Script", assets: "MediaAsset[]", preset: "string" },
    outputSchema: { video: "MediaAsset" },
    systemInstructions: "Honest: report when FFmpeg is unavailable.",
    tools: ["ffmpeg_compose"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 120000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.thumbnail,
    name: "Thumbnail Agent",
    version: "1.0.0",
    role: "custom",
    description: "Extracts a thumbnail frame from the composed video.",
    capabilities: ["thumbnail"],
    requiredPermissions: [],
    inputSchema: { script: "Script", video: "MediaAsset" },
    outputSchema: { thumbnail: "MediaAsset" },
    systemInstructions: "Never fabricate the thumbnail.",
    tools: ["ffmpeg_thumbnail"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 30000,
    retryPolicy: RETRY,
    validationRules: { failOnError: false, minConfidence: 0.3 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.compliance,
    name: "Compliance Agent",
    version: "1.0.0",
    role: "custom",
    description: "Authoritative compliance pass: script/hook/CTA/demo-label checks.",
    capabilities: ["compliance_review"],
    requiredPermissions: [],
    inputSchema: { script: "Script", demoContent: "boolean" },
    outputSchema: { passed: "boolean", blocked: "boolean", flags: "array" },
    systemInstructions: "Compliance is authoritative; block on high severity.",
    tools: ["compliance_rules"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 10000,
    retryPolicy: { maxRetries: 1, backoffMs: 500 },
    validationRules: { failOnError: true, minConfidence: 0 },
    status: "active",
  },
  {
    id: MARKETING_AGENT_IDS.publish,
    name: "Publish Agent",
    version: "1.0.0",
    role: "custom",
    description: "Out-of-band publish through configured channel adapters (gated by APPROVED).",
    capabilities: ["publish_content"],
    requiredPermissions: [],
    inputSchema: { creativeId: "string", channels: "string[]" },
    outputSchema: { published: "array", blocked: "array" },
    systemInstructions: "Only publish APPROVED content via real adapters.",
    tools: ["channel_adapters"],
    modelConfiguration: DETERMINISTIC,
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 1, backoffMs: 1000 },
    validationRules: { failOnError: false, minConfidence: 0 },
    status: "active",
  },
];

let registered = false;

export function ensureMarketingAgentsRegistered(): void {
  if (registered) return;
  registered = true;
  for (const agent of MARKETING_AGENT_CONTRACTS) {
    registerAgentContract(agent);
  }
}

ensureMarketingAgentsRegistered();