import { ExtensionRecord, PluginRecord } from "./types";

/**
 * Built-in AlgoVault plugin & extension catalog.
 *
 * These records define the first-class intelligence tools installed into the
 * marketplace. Every entry here has a real runtime implementation registered
 * in `lib/plugins/runtime/analyzers.ts` — nothing here is a demo card.
 *
 * The catalog is seeded into Firebase Realtime Database by
 * `lib/plugins/seed.ts` (idempotent, admin-gated).
 */

export const ADMIN_UID = "admin";

function record(
    input: Omit<PluginRecord, "rating" | "installs" | "activeUsers" | "versionHistory" | "createdAt" | "updatedAt" | "lastUpdated">
): PluginRecord {
    const version = input.manifest.version;
    return {
        ...input,
        rating: { average: 0, count: 0, distribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 }, updatedAt: 0 },
        installs: 0,
        activeUsers: 0,
        versionHistory: [version],
        createdAt: 0,
        updatedAt: 0,
        lastUpdated: 0,
    };
}

export const BUILTIN_PLUGINS: PluginRecord[] = [
    record({
        id: "strategy-dna",
        name: "strategy-dna",
        displayName: "Strategy DNA",
        slug: "strategy-dna",
        version: "1.0.0",
        description:
            "Analyzes your historical strategy and trading data to discover recurring characteristics: market regimes, sessions, holding durations, entry timing, market structure, and the conditions that historically surround your wins and losses.",
        type: "plugin",
        category: "trading-intelligence",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { trading_history: true, strategy_data: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Regime & session analysis",
            "Holding duration analysis",
            "Entry timing analysis",
            "Win / loss condition profiling",
            "Recurring setup characteristics",
            "Potential failure conditions",
        ],
        supportedMarkets: ["Any connected bot symbol"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "strategy-dna",
            displayName: "Strategy DNA",
            version: "1.0.0",
            type: "plugin",
            category: "trading-intelligence",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { trading_history: true, strategy_data: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["plugin.execution.completed"],
            emits: ["strategy.pattern.detected"],
            runtime: { handler: "strategy_dna", interval: "manual", timeoutMs: 20000, sources: ["bot_trades", "market_data"] },
        },
        documentation: [
            "## Strategy DNA",
            "Strategy DNA analyzes your historical bot trades to profile how your strategies behave:",
            "",
            "- **Market regime** — trending/ranging/volatile conditions in which the strategy performed",
            "- **Session profile** — which trading sessions produced most of the realized P/L",
            "- **Holding duration** — average, shortest and longest time in market",
            "- **Entry timing** — typical entry hour and time-of-week distribution",
            "- **Win/loss conditions** — shared characteristics around winning and losing outcomes",
            "",
            "Output is a factual profile computed from your recorded trade history. It is not a prediction.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — trade-history profiling from connected bots." }],
    }),
    record({
        id: "trading-behavior-intelligence",
        name: "trading-behavior-intelligence",
        displayName: "Trading Behavior Intelligence",
        slug: "trading-behavior-intelligence",
        version: "1.0.0",
        description:
            "Detects factual behavioral patterns in your trading activity: overtrading, post-loss behavior, post-streak behavior, risk scaling changes, entry-timing repetition and session-specific habits — based only on recorded data.",
        type: "plugin",
        category: "behavioral-analytics",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { trading_history: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Overtrading detection",
            "Post-loss behavior tracking",
            "Post-winning-streak behavior",
            "Risk scaling changes",
            "Session-specific habits",
            "Entry timing repetition",
        ],
        supportedMarkets: ["Any connected bot symbol"],
        supportedNotifications: ["In-app", "Email"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "trading-behavior-intelligence",
            displayName: "Trading Behavior Intelligence",
            version: "1.0.0",
            type: "plugin",
            category: "behavioral-analytics",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { trading_history: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["plugin.execution.completed"],
            emits: ["behavior.pattern.detected"],
            runtime: { handler: "behavior_intelligence", interval: "manual", timeoutMs: 20000, sources: ["bot_trades"] },
        },
        documentation: [
            "## Trading Behavior Intelligence",
            "Offers factual observations based on your historical activity:",
            "",
            "- Frequency of trades per session / hour",
            "- Activity immediately after losses (repeat entries vs. cool-down)",
            "- Activity after winning streaks",
            "- Position sizing changes over time",
            "- Overtrading windows (trade count vs. long-term average)",
            "",
            "The plugin reports what the data shows. It does not make psychological diagnoses",
            "and never claims your future outcomes.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — recorded-data behavior profiling." }],
    }),
    record({
        id: "counterfactual-lab",
        name: "counterfactual-lab",
        displayName: "Counterfactual Lab",
        slug: "counterfactual-lab",
        version: "1.0.0",
        description:
            "Explore historical 'what if' scenarios against your own trade history — different position size, confirmation delay, stop distance, or stopping after two consecutive losses. Labeled clearly as historical simulation.",
        type: "plugin",
        category: "trading-intelligence",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { trading_history: true, strategy_data: true, ai_analysis: true },
        capabilities: [
            "Position-size counterfactuals",
            "Stop-distance counterfactuals",
            "Consecutive-loss stop rules",
            "Confirmation-delay scenarios",
            "Historical simulation results",
        ],
        supportedMarkets: ["Any connected bot symbol"],
        supportedNotifications: ["In-app"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "counterfactual-lab",
            displayName: "Counterfactual Lab",
            version: "1.0.0",
            type: "plugin",
            category: "trading-intelligence",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { trading_history: true, strategy_data: true, ai_analysis: true },
            subscribes: [],
            emits: ["plugin.counterfactual.completed"],
            runtime: { handler: "counterfactual_lab", interval: "manual", timeoutMs: 20000, sources: ["bot_trades"] },
        },
        documentation: [
            "## Counterfactual Lab",
            "Pick a scenario (size multiplier, stop distance, loss-streak stop, or confirmation delay)",
            "and the lab re-runs your recorded trade history under those rules.",
            "",
            "Every result is labeled **Historical Analysis**. It simulates what the recorded",
            "data would have looked like — it is not a prediction and not investment advice.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — historical what-if scenarios." }],
    }),
    record({
        id: "trade-correlation-intelligence",
        name: "trade-correlation-intelligence",
        displayName: "Trade Correlation Intelligence",
        slug: "trade-correlation-intelligence",
        version: "1.0.0",
        description:
            "Detects hidden correlation and shared exposure across your open positions — USD exposure, gold sensitivity, DXY influence, risk-on/risk-off clustering — so several 'different' positions are never secretly one big bet.",
        type: "plugin",
        category: "correlation-analysis",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { portfolio_data: true, trading_history: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Cross-asset exposure mapping",
            "USD / gold / DXY sensitivity",
            "Risk-on / risk-off clustering",
            "Correlated position alerts",
        ],
        supportedMarkets: ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "DXY", "BTCUSD", "ETHUSD", "US30", "NAS100"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "trade-correlation-intelligence",
            displayName: "Trade Correlation Intelligence",
            version: "1.0.0",
            type: "plugin",
            category: "correlation-analysis",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { portfolio_data: true, trading_history: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["risk.threshold.reached"],
            emits: ["correlation.exposure.detected"],
            runtime: { handler: "correlation_intelligence", interval: "daily", timeoutMs: 20000, sources: ["positions", "market_data"] },
        },
        documentation: [
            "## Trade Correlation Intelligence",
            "Builds a correlation/exposure map from your currently open positions:",
            "",
            "- Positions sharing a currency pair (e.g. multiple EUR pairs → EUR exposure)",
            "- Gold-correlated pairs (AUD, JPY crosses vs XAUUSD)",
            "- DXY-sensitive instruments",
            "- Crypto risk-sentiment clusters",
            "",
            "Useful for identifying unintended concentration. Correlation ≠ guaranteed co-movement.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — position correlation mapping." }],
    }),
    record({
        id: "setup-fingerprint",
        name: "setup-fingerprint",
        displayName: "Setup Fingerprint",
        slug: "setup-fingerprint",
        version: "1.0.0",
        description:
            "Fingerprints your historical setups (session, volatility, regime, structure, momentum, distance from levels, entry timing, holding duration) and compares current live conditions against your library of past setups.",
        type: "plugin",
        category: "trading-intelligence",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { trading_history: true, market_data: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Multidimensional setup fingerprinting",
            "Live condition comparison",
            "Historical setup similarity scoring",
            "Context-aware setup alerts",
        ],
        supportedMarkets: ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "US30", "NAS100", "BTCUSD", "ETHUSD"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "setup-fingerprint",
            displayName: "Setup Fingerprint",
            version: "1.0.0",
            type: "plugin",
            category: "trading-intelligence",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { trading_history: true, market_data: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["market.condition.detected"],
            emits: ["strategy.pattern.detected", "market.condition.detected"],
            runtime: { handler: "setup_fingerprint", interval: "5m", timeoutMs: 20000, sources: ["bot_trades", "market_data"] },
        },
        documentation: [
            "## Setup Fingerprint",
            "On each run the plugin computes a current condition fingerprint and compares it",
            "with historical fingerprints synthesized from your bot trades.",
            "",
            "A high 'historical similarity' simply means today's conditions resemble past ones",
            "in measurable dimensions. It is contextual analysis — not a trade recommendation,",
            "and it never promises an outcome.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — fingerprint comparison engine." }],
    }),
    record({
        id: "market-opportunity-agent",
        name: "market-opportunity-agent",
        displayName: "Market Opportunity Agent",
        slug: "market-opportunity-agent",
        version: "1.0.0",
        description:
            "A background agent that monitors instruments you select and detects market conditions matching criteria you configure (structure, volatility, momentum, regime, session, historical fingerprints). Presents analysis, context and evidence — never a buy/sell instruction.",
        type: "plugin",
        category: "market-monitoring",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { market_data: true, news_data: true, trading_history: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Multi-symbol background monitoring",
            "Configurable condition criteria",
            "Market structure & regime context",
            "Historical similarity context",
            "Severity-controlled alerts",
        ],
        supportedMarkets: ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "US30", "NAS100", "SPX500", "BTCUSD", "ETHUSD", "SOLUSD"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "market-opportunity-agent",
            displayName: "Market Opportunity Agent",
            version: "1.0.0",
            type: "plugin",
            category: "market-monitoring",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { market_data: true, news_data: true, trading_history: true, strategy_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["market.condition.detected", "strategy.pattern.detected"],
            emits: ["market.condition.detected", "market.opportunity.detected"],
            runtime: { handler: "opportunity_agent", interval: "5m", timeoutMs: 20000, sources: ["market_data", "news_data"] },
        },
        documentation: [
            "## Market Opportunity Agent",
            "Runs in the background on the interval you choose and checks selected symbols",
            "against the criteria you configure: market structure, volatility, momentum,",
            "regime, session and similarity to your historical setup fingerprints.",
            "",
            "When a condition is detected you receive a structured alert with symbol, regime,",
            "momentum, volatility, similarity and context. AlgoVault never tells you to buy or",
            "sell, and never represents a detected condition as guaranteed profit.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — background opportunity monitoring." }],
    }),
    record({
        id: "market-anomaly-agent",
        name: "market-anomaly-agent",
        displayName: "Market Anomaly Agent",
        slug: "market-anomaly-agent",
        version: "1.0.0",
        description:
            "A background agent that watches for unusual market conditions — abnormal volatility, unusual price movement, regime changes, abnormal spread, or deviation from baseline — and sends an alert with context.",
        type: "plugin",
        category: "market-monitoring",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { market_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Abnormal volatility detection",
            "Unusual price movement flags",
            "Sudden regime change alerts",
            "Abnormal spread detection",
            "Baseline deviation tracking",
        ],
        supportedMarkets: ["XAUUSD", "EURUSD", "GBPUSD", "USDJPY", "US30", "NAS100", "BTCUSD", "ETHUSD"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "market-anomaly-agent",
            displayName: "Market Anomaly Agent",
            version: "1.0.0",
            type: "plugin",
            category: "market-monitoring",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { market_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: [],
            emits: ["market.anomaly.detected"],
            runtime: { handler: "anomaly_agent", interval: "5m", timeoutMs: 20000, sources: ["market_data"] },
        },
        documentation: [
            "## Market Anomaly Agent",
            "Monitors selected symbols and compares live conditions against a rolling baseline.",
            "Flags abnormal volatility (ATR vs. baseline), unusual single-bar moves, sudden regime",
            "shifts and abnormal spreads where data is available.",
            "",
            "Alerts carry the measured deviation so you can judge severity yourself.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — anomaly detection agent." }],
    }),
    record({
        id: "news-impact-agent",
        name: "news-impact-agent",
        displayName: "News Impact Agent",
        slug: "news-impact-agent",
        version: "1.0.0",
        description:
            "Monitors the economic calendar, maps events to instruments you select, notifies you before scheduled events, and detects post-event volatility — with factual context and no directional certainty claims.",
        type: "plugin",
        category: "news-intelligence",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { news_data: true, market_data: true, notifications: true, scheduler: true },
        capabilities: [
            "Event-to-instrument mapping",
            "Pre-event notifications",
            "Post-event volatility tracking",
            "High-impact event filtering",
        ],
        supportedMarkets: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "US30", "NAS100"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "news-impact-agent",
            displayName: "News Impact Agent",
            version: "1.0.0",
            type: "plugin",
            category: "news-intelligence",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { news_data: true, market_data: true, notifications: true, scheduler: true },
            subscribes: [],
            emits: ["news.event.upcoming", "news.post_event_volatility"],
            runtime: { handler: "news_impact", interval: "hourly", timeoutMs: 20000, sources: ["news_data", "market_data"] },
        },
        documentation: [
            "## News Impact Agent",
            "Uses the AlgoVault economic calendar to map events to your chosen instruments.",
            "Notifies you before high-impact events and tracks post-event volatility.",
            "",
            "The plugin states what is scheduled and what volatility was observed. It never",
            "claims to know which direction an event will move a market.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — economic calendar monitoring." }],
    }),
    record({
        id: "risk-guardian",
        name: "risk-guardian",
        displayName: "Risk Guardian",
        slug: "risk-guardian",
        version: "1.0.0",
        description:
            "A background guardian that monitors the risk limits you define — drawdown threshold, exposure concentration, correlated exposure, position count and unusual risk increases — using your connected account and position data.",
        type: "plugin",
        category: "risk-management",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { portfolio_data: true, trading_history: true, account_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Drawdown threshold alerts",
            "Exposure concentration alerts",
            "Correlated exposure alerts",
            "Position count limits",
            "Risk-change detection",
        ],
        supportedMarkets: ["Any connected account"],
        supportedNotifications: ["In-app", "Email", "Telegram", "Discord"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "risk-guardian",
            displayName: "Risk Guardian",
            version: "1.0.0",
            type: "plugin",
            category: "risk-management",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { portfolio_data: true, trading_history: true, account_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["market.anomaly.detected"],
            emits: ["risk.threshold.reached"],
            runtime: { handler: "risk_guardian", interval: "5m", timeoutMs: 20000, sources: ["positions", "bot_trades"] },
        },
        documentation: [
            "## Risk Guardian",
            "Watch your configured risk limits 24/7 while the plugin is active:",
            "",
            "- maximum drawdown over a rolling window",
            "- maximum exposure concentration per symbol / currency",
            "- correlated exposure cluster size",
            "- maximum concurrent position count",
            "- unusual jump in risk between runs",
            "",
            "The plugin alerts you when a limit is hit. It never places, modifies or closes orders.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — configurable risk limits." }],
    }),
    record({
        id: "personal-market-intelligence",
        name: "personal-market-intelligence",
        displayName: "Personal Market Intelligence",
        slug: "personal-market-intelligence",
        version: "1.0.0",
        description:
            "Learns patterns from your own historical trading data and tells you how many past situations resemble current market conditions — common characteristics included. Contextual analysis, not prediction.",
        type: "plugin",
        category: "ai-assistant",
        pricing: { type: "free", price: 0, currency: "usd" },
        permissions: { trading_history: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
        capabilities: [
            "Personal pattern library",
            "Current-condition comparison",
            "Similar historical situations",
            "Common characteristic summaries",
        ],
        supportedMarkets: ["Any connected bot symbol"],
        supportedNotifications: ["In-app", "Email"],
        creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
        status: "published",
        isAIGenerated: false,
        manifest: {
            name: "personal-market-intelligence",
            displayName: "Personal Market Intelligence",
            version: "1.0.0",
            type: "plugin",
            category: "ai-assistant",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { trading_history: true, market_data: true, ai_analysis: true, notifications: true, scheduler: true },
            subscribes: ["market.condition.detected"],
            emits: ["strategy.pattern.detected"],
            runtime: { handler: "personal_intelligence", interval: "1m", timeoutMs: 20000, sources: ["bot_trades", "market_data"] },
        },
        documentation: [
            "## Personal Market Intelligence",
            "Builds a personal pattern library from your trade history and compares it to",
            "current market conditions across measurable dimensions.",
            "",
            "Output looks like: 'current conditions resemble N historical situations; common",
            "characteristics: …'. This is contextual analysis — it makes no prediction.",
        ].join("\n"),
        changelog: [{ version: "1.0.0", note: "Initial release — personal pattern comparison." }],
    }),
];

export const BUILTIN_EXTENSIONS: ExtensionRecord[] = [
    {
        ...record({
            id: "webhook-extension",
            name: "webhook-extension",
            displayName: "Webhook Extension",
            slug: "webhook-extension",
            version: "1.0.0",
            description:
                "Consume AlgoVault plugin events from any external application through a signed webhook endpoint. Choose which plugins and event types to forward.",
            type: "extension",
            category: "external-integration",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { webhooks: true, notifications: true, scheduler: true },
            capabilities: ["Signed event delivery", "Event type filtering", "Retry on failure"],
            supportedMarkets: ["—"],
            supportedNotifications: ["Webhook"],
            creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
            status: "published",
            isAIGenerated: false,
            manifest: {
                name: "webhook-extension",
                displayName: "Webhook Extension",
                version: "1.0.0",
                type: "extension",
                category: "external-integration",
                pricing: { type: "free", price: 0, currency: "usd" },
                permissions: { webhooks: true, notifications: true, scheduler: true },
                subscribes: [],
                emits: [],
                runtime: { handler: "webhook_extension", interval: "event", timeoutMs: 10000, sources: ["events"] },
            },
        }),
        extensionType: "webhook",
        endpoints: ["POST /api/plugins/webhook/stream"],
    },
    {
        ...record({
            id: "telegram-extension",
            name: "telegram-extension",
            displayName: "Telegram Extension",
            slug: "telegram-extension",
            version: "1.0.0",
            description:
                "Extends your existing Telegram connection to receive selected AlgoVault plugin intelligence — it reuses the AlgoVault Telegram bot, not a separate system.",
            type: "extension",
            category: "external-integration",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { telegram: true, notifications: true },
            capabilities: ["Selected plugin alerts via Telegram", "Reuses existing bot connection"],
            supportedMarkets: ["—"],
            supportedNotifications: ["Telegram"],
            creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
            status: "published",
            isAIGenerated: false,
            manifest: {
                name: "telegram-extension",
                displayName: "Telegram Extension",
                version: "1.0.0",
                type: "extension",
                category: "external-integration",
                pricing: { type: "free", price: 0, currency: "usd" },
                permissions: { telegram: true, notifications: true },
                subscribes: [],
                emits: [],
                runtime: { handler: "telegram_extension", interval: "manual", timeoutMs: 10000, sources: ["notifications"] },
            },
        }),
        extensionType: "telegram",
    },
    {
        ...record({
            id: "discord-extension",
            name: "discord-extension",
            displayName: "Discord Extension",
            slug: "discord-extension",
            version: "1.0.0",
            description:
                "Expose selected AlgoVault plugin intelligence through your existing Discord webhook channel. Reuses your AlgoVault Discord integration.",
            type: "extension",
            category: "external-integration",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { discord: true, notifications: true },
            capabilities: ["Selected plugin alerts via Discord", "Reuses existing webhook"],
            supportedMarkets: ["—"],
            supportedNotifications: ["Discord"],
            creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
            status: "published",
            isAIGenerated: false,
            manifest: {
                name: "discord-extension",
                displayName: "Discord Extension",
                version: "1.0.0",
                type: "extension",
                category: "external-integration",
                pricing: { type: "free", price: 0, currency: "usd" },
                permissions: { discord: true, notifications: true },
                subscribes: [],
                emits: [],
                runtime: { handler: "discord_extension", interval: "manual", timeoutMs: 10000, sources: ["notifications"] },
            },
        }),
        extensionType: "discord",
    },
    {
        ...record({
            id: "browser-extension",
            name: "browser-extension",
            displayName: "Browser Extension",
            slug: "browser-extension",
            version: "1.0.0",
            description:
                "Interact with AlgoVault intelligence while browsing supported trading websites via the AlgoVault Browser Extension companion.",
            type: "extension",
            category: "workflow",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { market_data: true, ai_analysis: true, notifications: true },
            capabilities: ["'Analyze with AlgoVault' context action"],
            supportedMarkets: ["Supported trading websites"],
            supportedNotifications: ["In-app", "Email"],
            creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
            status: "published",
            isAIGenerated: false,
            manifest: {
                name: "browser-extension",
                displayName: "Browser Extension",
                version: "1.0.0",
                type: "extension",
                category: "workflow",
                pricing: { type: "free", price: 0, currency: "usd" },
                permissions: { market_data: true, ai_analysis: true, notifications: true },
                subscribes: [],
                emits: [],
                runtime: { handler: "browser_extension", interval: "manual", timeoutMs: 10000, sources: ["market_data"] },
            },
        }),
        extensionType: "browser",
    },
    {
        ...record({
            id: "tradingview-companion",
            name: "tradingview-companion",
            displayName: "TradingView Companion",
            slug: "tradingview-companion",
            version: "1.0.0",
            description:
                "Bring supported AlgoVault analysis and context into TradingView workflows through a companion integration where technically possible.",
            type: "extension",
            category: "workflow",
            pricing: { type: "free", price: 0, currency: "usd" },
            permissions: { market_data: true, ai_analysis: true, notifications: true },
            capabilities: ["TradingView workflow companion"],
            supportedMarkets: ["TradingView-symbols"],
            supportedNotifications: ["In-app"],
            creator: { uid: ADMIN_UID, name: "AlgoVault Team", kind: "admin" },
            status: "published",
            isAIGenerated: false,
            manifest: {
                name: "tradingview-companion",
                displayName: "TradingView Companion",
                version: "1.0.0",
                type: "extension",
                category: "workflow",
                pricing: { type: "free", price: 0, currency: "usd" },
                permissions: { market_data: true, ai_analysis: true, notifications: true },
                subscribes: [],
                emits: [],
                runtime: { handler: "tradingview_companion", interval: "manual", timeoutMs: 10000, sources: ["market_data"] },
            },
        }),
        extensionType: "tradingview",
    },
];

export const PLUGIN_CATEGORIES: { id: string; name: string; description: string }[] = [
    { id: "trading-intelligence", name: "Trading Intelligence", description: "Analyze markets, strategies and setups." },
    { id: "risk-management", name: "Risk Management", description: "Guard your limits and monitor exposure." },
    { id: "market-monitoring", name: "Market Monitoring", description: "Background agents watching live markets." },
    { id: "behavioral-analytics", name: "Behavioral Analytics", description: "Factual patterns from your own activity." },
    { id: "correlation-analysis", name: "Correlation Analysis", description: "Hidden exposure and co-movement." },
    { id: "automation", name: "Automation", description: "Scheduled intelligence and workflows." },
    { id: "external-integration", name: "External Integration", description: "Connect AlgoVault to outside tools." },
    { id: "workflow", name: "Workflow", description: "Companions for the way you work." },
    { id: "news-intelligence", name: "News Intelligence", description: "Economic events and impact context." },
    { id: "ai-assistant", name: "AI Assistant", description: "Personal intelligence assistants." },
];

export const CATALOG = {
    plugins: BUILTIN_PLUGINS,
    extensions: BUILTIN_EXTENSIONS,
    categories: PLUGIN_CATEGORIES,
};

export function findBuiltinPlugin(id: string): PluginRecord | undefined {
    return BUILTIN_PLUGINS.find((p) => p.id === id || p.slug === id);
}

export function findBuiltinExtension(id: string): ExtensionRecord | undefined {
    return BUILTIN_EXTENSIONS.find((e) => e.id === id || e.slug === id);
}