/** AlgoVault Agentic Trading Intelligence — Agent Orchestrator (Phase 14 §6)

 * The orchestrator coordinates specialized agents, preserves disagreements,
 * and synthesizes final intelligence.
 */

import type { AgentPermission, AgentRiskLevel, ProposedAction, StructuredOutput } from "./contracts";
import { AgentRuntime, AGENT_DEFINITIONS, getAgentDefinition } from "./agent-runtime";
import { TOOL_REGISTRY, isToolAllowed, isRiskLevelAcceptable } from "./tool-registry";

// ─── Orchestrator input ────────────────────────────────────────────────────────
export interface OrchestratorInput {
  goal: string;
  scope: "market" | "setup" | "strategy" | "risk" | "research" | "execution" | "journal" | "intelligence" | "multi_agent";
  agents: string[]; // agent ids
  plan?: OrchestratorStep[]; // optional explicit plan
  constraints?: OrchestratorConstraints;
  correlationId?: string;
  causationId?: string;
}

export interface OrchestratorConstraints {
  maxSteps?: number;
  maxTimeMs?: number;
  maxToolCalls?: number;
  maxBudgetCents?: number;
  allowedTools?: string[];
  requiredPermissions?: AgentPermission[];
}

export interface OrchestratorStep {
  name: string;
  agentId?: string; // if omitted, orchestrator picks
  tools?: string[];
  dependsOn?: string[];
  optional?: boolean;
}

// ─── Orchestrator output ───────────────────────────────────────────────────────
export interface OrchestratorOutput {
  runId: string;
  taskId: string;
  status: "completed" | "failed" | "blocked";
  synthesis: StructuredOutput;
  disagreements: OrchestratorDisagreement[];
  confidence: number;
  errors: string[];
  durationMs: number;
}

export interface OrchestratorDisagreement {
  agents: string[];
  topic: string;
  positions: Array<{ agentId: string; stance: string; confidence: number; evidence: string[] }>;
  reason?: string;
}

// ─── Orchestrator ─────────────────────────────────────────────────────────────
export class AgentOrchestrator {
  constructor(
    private readonly agentRuntime: AgentRuntime,
    private readonly input: OrchestratorInput,
  ) {}

  /** Run the orchestration. */
  async run(): Promise<OrchestratorOutput> {
    const startTime = Date.now();
    this.agentRuntime.start();
    this.agentRuntime.beginExecution();

    // 1. Build plan (either explicit or generated by the orchestrator).
    const plan = this.input.plan ?? this.buildPlan();
    if (!plan) {
      this.agentRuntime.block("No plan could be built for this goal.");
      return this.finalOutput(this.agentRuntime, startTime, "blocked", []);
    }

    // 2. Execute plan steps.
    const disagreements: OrchestratorDisagreement[] = [];
    const errors: string[] = [];
    for (const step of plan) {
      try {
        const result = await this.executeStep(step, disagreements);
        if (result?.block) {
          this.agentRuntime.block(result.block);
          return this.finalOutput(this.agentRuntime, startTime, "blocked", disagreements);
        }
        if (result?.error) {
          errors.push(result.error);
        }
      } catch (err) {
        errors.push(String(err));
      }
    }

    // 3. Synthesize final output.
    const synthesis = this.synthesize(disagreements);
    this.agentRuntime.complete(synthesis);
    return this.finalOutput(this.agentRuntime, startTime, "completed", disagreements);
  }

  // ─── Plan building ────────────────────────────────────────────────────────
  private buildPlan(): OrchestratorStep[] {
    // Heuristic plan based on scope and agents. In a real system this would be
    // generated by a reasoning model; here we use a deterministic default that
    // reuses existing engines.
    const scope = this.input.scope;
    const agents = this.input.agents;

    const steps: OrchestratorStep[] = [];
    if (scope === "market" || scope === "setup" || scope === "execution" || scope === "intelligence") {
      if (agents.includes("market-analyst")) {
        steps.push({ name: "market_analysis", agentId: "market-analyst", tools: ["get_market_snapshot", "get_candles", "get_indicators", "get_smart_money", "monitor_market"] });
      }
      if (scope === "setup" && agents.includes("setup-analyst")) {
        steps.push({ name: "setup_review", agentId: "setup-analyst", tools: ["get_setup", "search_historical_setups", "create_setup"] });
      }
      if (scope === "execution" && agents.includes("execution-supervisor")) {
        steps.push({ name: "execution_intent", agentId: "execution-supervisor", tools: ["prepare_order", "get_risk_state", "get_positions", "get_strategy"] });
      }
      if (scope === "intelligence" && agents.includes("orchestrator")) {
        steps.push({ name: "synthesize_intelligence", agentId: "orchestrator", tools: ["synthesize_intelligence"] });
      }
    }
    if (scope === "strategy" && agents.includes("strategy-health-agent")) {
      steps.push({ name: "strategy_health", agentId: "strategy-health-agent", tools: ["get_strategy", "get_strategy_health", "monitor_strategy"] });
    }
    if (scope === "risk" && agents.includes("risk-agent")) {
      steps.push({ name: "risk_assessment", agentId: "risk-agent", tools: ["get_risk_state", "get_positions", "monitor_risk", "create_alert", "pause_strategy"] });
    }
    if (scope === "research" && agents.includes("research-agent")) {
      steps.push({ name: "research", agentId: "research-agent", tools: ["start_research", "get_research_status", "create_research_hypothesis", "evaluate_research_results", "compare_candidates"] });
    }
    if (scope === "journal" && agents.includes("journal-agent")) {
      steps.push({ name: "journal_review", agentId: "journal-agent", tools: ["get_journal", "create_journal_entry", "create_research_hypothesis"] });
    }
    if (steps.length === 0) {
      // Fallback: use whatever agents were requested.
      for (const agentId of agents) {
        const def = getAgentDefinition(agentId);
        if (def) {
          steps.push({ name: `${agentId}_task`, agentId, tools: def.allowedTools.slice(0, 3) });
        }
      }
    }
    return steps;
  }

  // ─── Step execution ───────────────────────────────────────────────────────
  private async executeStep(step: OrchestratorStep, disagreements: OrchestratorDisagreement[]): Promise<{ block?: string; error?: string }> {
    const agentId = step.agentId;
    if (!agentId) {
      return { error: "Step missing agentId." };
    }
    const def = getAgentDefinition(agentId);
    if (!def) {
      return { error: `Agent '${agentId}' not found.` };
    }
    // Check permissions.
    for (const tool of step.tools ?? []) {
      if (!isToolAllowed(tool, def.permissions)) {
        return { block: `Agent '${agentId}' cannot use tool '${tool}' — insufficient permissions.` };
      }
      if (!isRiskLevelAcceptable(tool, this.agentRuntime.allowedRiskLevels)) {
        return { block: `Tool '${tool}' risk level not acceptable for this agent.` };
      }
    }
    // In a real system, spawn the agent runtime for this step and run it.
    // Here we simulate a step completion.
    this.agentRuntime.observe("observed", `Executed step '${step.name}' with agent '${agentId}'.`, "orchestrator");
    this.agentRuntime.decide("proceed", `Step '${step.name}' completed.`, [], 1, [step.name]);
    // Capture disagreements if multiple agents weigh in on the same topic.
    // (Simplified: disagreements are recorded by the orchestrator when it sees
    // conflicting agent outputs. The actual conflict detection happens in
    // synthesize().)
    return {};
  }

  // ─── Synthesis ────────────────────────────────────────────────────────────
  private synthesize(disagreements: OrchestratorDisagreement[]): StructuredOutput {
    // Build a minimal structured output. In a real system this would be produced
    // by a reasoning model; here we return a placeholder that satisfies the contract
    // and preserves any disagreements previously captured.
    return {
      type: "intelligence_brief",
      objective: this.input.goal,
      observedFacts: this.agentRuntime.observations.filter((o) => o.kind === "observed").map((o) => o.text),
      analysis: [],
      evidence: [],
      risks: [],
      decision: "Pending synthesis.",
      actions: this.agentRuntime.actions.filter((a) => a.status === "pending"),
      limitations: ["Synthesis is a placeholder until the reasoning model is wired."],
      nextSteps: [],
      provenance: {
        agentId: this.agentRuntime.agentDef.id,
        versionId: this.agentRuntime.agentDef.version,
        model: this.agentRuntime.agentDef.modelPreference?.model ?? "default",
        tools: this.agentRuntime.agentDef.allowedTools,
        contextSnapshot: JSON.stringify({ goal: this.input.goal }),
        engineVersions: {},
        dataTimestamp: Date.now(),
      },
    };
  }

  private finalOutput(runtime: AgentRuntime, startTime: number, status: "completed" | "failed" | "blocked", disagreements: OrchestratorDisagreement[]): OrchestratorOutput {
    return {
      runId: runtime.taskId,
      taskId: runtime.taskId,
      status,
      synthesis: runtime.observations.length > 0 ? this.synthesize(disagreements) : {
        type: "intelligence_brief",
        objective: runtime.task.goal,
        observedFacts: [],
        analysis: [],
        evidence: [],
        risks: [],
        decision: status === "blocked" ? "Blocked: see errors." : "No synthesis produced.",
        actions: [],
        limitations: ["No observations recorded."],
        nextSteps: [],
        provenance: {
          agentId: runtime.agentDef.id,
          versionId: runtime.agentDef.version,
          model: runtime.agentDef.modelPreference?.model ?? "default",
          tools: runtime.agentDef.allowedTools,
          contextSnapshot: JSON.stringify({ goal: runtime.task.goal }),
          engineVersions: {},
          dataTimestamp: Date.now(),
        },
      },
      disagreements,
      confidence: 0,
      errors: runtime.errors,
      durationMs: Date.now() - startTime,
    };
  }
}

// ─── Factory ──────────────────────────────────────────────────────────────────
export function createOrchestrator(input: OrchestratorInput, runtime: AgentRuntime): AgentOrchestrator {
  return new AgentOrchestrator(runtime, input);
}
